# Site settings
title:       Bo's Blog
email:       bonny95@gmail.com
author:      Bo Yang
description: "Bo's blog."
baseurl:     ""
url:         "http://www.bo-yang.net/"
date_format: "%b %-d, %Y"

# Google services
google_analytics: UA-50551633-1
google_verification:

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:   boyang

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: true
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username:    bo-yang
bitbucket_username:
stackoverflow_id:   boyang
twitter_username:   bonnyang
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:  boyanglink
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Leave Message'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'


# Build settings
markdown:     kramdown
kramdown:
    input:    GFM
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
